title = "Patricks Blog"
baseURL = "https://patricks-blog.onrender.com/"
languageCode = "de-de"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Ananke"
    weight = 1
    contentDir = "content"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Patrick Meyhöfer"
  favicon = ""
  site_logo = ""
  description = "Meine Gedanken"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/storminator89"


